# Generated by Django 5.2.17 on 2026-09-28 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_units_of_measure"),
        ("store", "0002_alter_stockmovement_document_type_issue_issueline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("grn", "GRN"),
                    ("issue", "Issue"),
                    ("return", "Return to store"),
                    ("transfer", "Transfer"),
                    ("adjustment", "Stock count adjustment"),
                    ("reversal", "Reversal"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_counts",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["store", "number"],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_quantity",
                    models.DecimalField(
                        decimal_places=3, editable=False, max_digits=14
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store.storeitem",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="store.stockcount",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_transit", "In transit"),
                            ("received", "Received"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="store.store",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="core.project",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "number"],
            },
        ),
        migrations.CreateModel(
            name="TransferLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "dispatch_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store.storeitem",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="store.transfer",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReversal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("grn", "GRN"),
                            ("issue", "Issue"),
                            ("return", "Return to store"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Stock count adjustment"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=15,
                    ),
                ),
                ("document_id", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reversed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "document_id"),
                        name="one_reversal_per_document",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stockcount",
            constraint=models.UniqueConstraint(
                fields=("store", "number"), name="unique_stock_count_number_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="unique_transfer_number_per_project"
            ),
        ),
    ]
