# Generated by Django 5.2.17 on 2026-09-29 08:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0003_variationorder"),
        ("store", "0003_alter_stockmovement_document_type_stockcount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="over_allowance_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Project Manager approval"),
                    ("posted", "Posted"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MaterialAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="e.g. 0.32 (t of cement per m³ of concrete).",
                        max_digits=10,
                    ),
                ),
                (
                    "wastage_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "boq_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_allowances",
                        to="boq.boqitem",
                    ),
                ),
                (
                    "store_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store.storeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["boq_item", "store_item"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("boq_item", "store_item"),
                        name="unique_allowance_per_boq_item_and_store_item",
                    )
                ],
            },
        ),
    ]
