# Generated by Django 5.2.17 on 2026-09-28 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                (
                    "logo",
                    models.FileField(blank=True, null=True, upload_to="company_logos/"),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[("SLE", "Sierra Leone Leone"), ("USD", "US Dollar")],
                        default="SLE",
                        max_length=3,
                    ),
                ),
                (
                    "tax_settings",
                    models.TextField(
                        blank=True,
                        help_text="Free-text notes on VAT/GST rates and rules until the reporting step (Section 7) needs structured tax fields.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("length", "Length"),
                            ("area", "Area"),
                            ("volume", "Volume"),
                            ("weight", "Weight"),
                            ("count", "Count"),
                            ("time", "Time"),
                            ("lump_sum", "Lump sum"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. BTR-2026", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("client", models.CharField(blank=True, max_length=255)),
                ("consultant_engineer", models.CharField(blank=True, max_length=255)),
                ("contract_number", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_sum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("SLE", "Sierra Leone Leone"), ("USD", "US Dollar")],
                        default="SLE",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        default="planning",
                        max_length=10,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("project_manager", "Project Manager"),
                            ("qs", "QS"),
                            ("site_engineer", "Site Engineer"),
                            ("storekeeper", "Storekeeper"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="projects",
                through="core.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("start_chainage", models.DecimalField(decimal_places=3, max_digits=8)),
                ("end_chainage", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "start_chainage"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="unique_membership_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("project", "code"), name="unique_section_code_per_project"
            ),
        ),
    ]
