# Generated by Django 5.2.17 on 2026-09-29 08:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_units_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="variance_amber_threshold_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("5"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="variance_red_threshold_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("10"), max_digits=5
            ),
        ),
    ]
