# Generated by Django 5.2.17 on 2026-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_variance_amber_threshold_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitofmeasure",
            name="type",
            field=models.CharField(
                choices=[
                    ("length", "Length"),
                    ("area", "Area"),
                    ("volume", "Volume"),
                    ("weight", "Weight"),
                    ("count", "Count"),
                    ("time", "Time"),
                    ("lump_sum", "Lump sum"),
                    ("haulage", "Haulage"),
                ],
                max_length=10,
            ),
        ),
    ]
