# Generated by Django 5.2.17 on 2026-09-28 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_seed_units_of_measure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BOQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("revision", "Revision"),
                            ("variation", "Variation"),
                        ],
                        default="original",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boqs",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "version_number"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "boq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="boq.boq",
                    ),
                ),
            ],
            options={
                "ordering": ["boq", "sort_order", "number"],
            },
        ),
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_reference",
                    models.CharField(help_text="e.g. 4.02", max_length=20),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("measured", "Measured"),
                            ("provisional_sum", "Provisional Sum"),
                            ("prime_cost", "Prime Cost"),
                            ("lump_sum", "Lump Sum"),
                            ("daywork", "Daywork"),
                            ("heading", "Heading"),
                        ],
                        default="measured",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=16,
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="boq.bill",
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="boq.boqitem",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="core.section",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["bill", "sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="boq",
            constraint=models.UniqueConstraint(
                fields=("project", "version_number"),
                name="unique_boq_version_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                fields=("boq", "number"), name="unique_bill_number_per_boq"
            ),
        ),
    ]
