# Generated by Django 5.2.17 on 2026-09-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boqitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("measured", "Measured"),
                    ("provisional_sum", "Provisional Sum"),
                    ("prime_cost", "Prime Cost"),
                    ("lump_sum", "Lump Sum"),
                    ("daywork", "Daywork"),
                    ("heading", "Heading"),
                ],
                max_length=20,
            ),
        ),
    ]
