# Generated by Django 5.2.17 on 2026-09-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0002_alter_boqitem_item_type"),
        ("core", "0002_seed_units_of_measure"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                (
                    "instructed_by",
                    models.CharField(
                        blank=True,
                        help_text="e.g. the client's engineer — not necessarily a system user.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "base_boq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variation_orders_based_on",
                        to="boq.boq",
                    ),
                ),
                (
                    "linked_boq",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variation_order",
                        to="boq.boq",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variation_orders",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "number"),
                        name="unique_vo_number_per_project",
                    )
                ],
            },
        ),
    ]
