# Generated by Django 5.2.17 on 2026-09-29 09:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0003_variationorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="boq",
            name="contingency_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="boq",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
    ]
