# Generated by Django 5.2.17 on 2026-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0004_boq_contingency_percent_boq_tax_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boqitem",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="boqitem",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
    ]
